### ISSUE TITLE
Unable to install on GitHub's macOS runners with Python 3.10

### ISSUE THREAD

**Issue by jwodder** [zarr-developers/numcodecs#326]
#### Minimal, reproducible code sample, a copy-pastable example if possible

A minimal GitHub actions workflow that reproduces the problem:

```yaml
name: Foo

on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  misc:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install --upgrade pip wheel
          pip install numcodecs
```

#### Problem description

Currently, installing the latest version of numcodecs (0.9.1) in one of GitHub Actions' macOS runners when using Python 3.10 fails with numerous compilation errors of the form `invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size` (full output can be found [here](https://github.com/jwodder/test/runs/6925157452?check_suite_focus=true)).  Of note is that installation was working as recently as 10:55 EDT today (June 16) but stopped working by 12:29 EDT.  In that time period, it appears that the software used by the macOS runners was updated; the old list of software can be found [here](https://github.com/actions/virtual-environments/blob/macOS-11/20220605.1/images/macos/macos-11-Readme.md), and new list of software is [here](https://github.com/actions/virtual-environments/blob/macOS-11/20220614.2/images/macos/macos-11-Readme.md).  From a cursory glance, the only possibly relevant difference I see is that Python 3.10 was updated from 3.10.4 to 3.10.5.

#### Version and installation information

Please provide the following:

* Value of ``numcodecs.__version__``: 0.9.1
* Version of Python interpreter: 3.10.5
* Operating system (Linux/Windows/Mac): macOS
* How NumCodecs was installed (e.g., "using pip into virtual environment", or "using conda") — using pip
